### ISSUE TITLE
bug: generate text feature not working properly  

### ISSUE THREAD

**Issue by ruru-m07** [fuma-nama/shark-chat-js#7]
![image](https://github.com/fuma-nama/shark-chat-js/assets/142723369/cafaa320-b88e-4dbf-beb2-9650d69cc1a3)

![image](https://github.com/fuma-nama/shark-chat-js/assets/142723369/13381ee2-bfb9-42f4-954a-4d6e1f8a4019)

**Comment by fuma-nama** [comment]
The AI service was down for a while. It's now working.

**Comment by ruru-m07** [comment]
Ohh thanks, @fuma-nama  now it working.

![image](https://github.com/fuma-nama/shark-chat-js/assets/142723369/06275f46-2c14-4330-9408-c855da3495bf)
